"""SQLAlchemy declarative base, naming convention, and shared column helpers.

An explicit constraint-naming convention makes Alembic autogenerate deterministic
(named constraints instead of backend-specific auto-names), which keeps migrations
stable across SQLite (dev) and PostgreSQL (prod).
"""

from __future__ import annotations

from datetime import datetime
from uuid import UUID, uuid4

from sqlalchemy import DateTime, MetaData, Uuid, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Deterministic constraint names -> stable autogenerated migrations.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base shared by every ORM model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def uuid_pk() -> Mapped[UUID]:
    """A UUID primary key column, generated application-side.

    ``Uuid`` maps to a native UUID on PostgreSQL and to a 32-char string on
    SQLite, so the same model works in dev and prod.
    """
    return mapped_column(Uuid, primary_key=True, default=uuid4)


class TimestampMixin:
    """Adds timezone-aware ``created_at`` / ``updated_at`` audit columns."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
